export enum supportedMethods {
  delete = "DELETE",
  get = "GET",
  head = "HEAD",
  patch = "PATCH",
  post = "POST",
  put = "PUT",
  options = "OPTIONS",
  propfind = "PROPFIND",
  proppatch = "PROPPATCH",
  mkcol = "MKCOL",
  copy = "COPY",
  move = "MOVE",
  lock = "LOCK",
  unlock = "UNLOCK",
  trace = "TRACE",
  search = "SEARCH",
}
